name: Deploy Docker image to Docker Hub

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
  steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: supermanchen/wakatime-sync
        username: ${{ secrets.DOCKER_USERNAME ***REMOVED******REMOVED***
        password: ${{ secrets.DOCKER_PASSWORD ***REMOVED******REMOVED***
