name: Deploy Docker

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME ***REMOVED******REMOVED***
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD ***REMOVED******REMOVED***
    - name: Build Docker Image
      run: docker build -t supermanchen/wakatime-sync .
    - name: Deploy to Docker Hub
      run: docker push supermanchen/wakatime-sync
