name: Update gist with WakaTime summary
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: superman66/wakatime-sync@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN ***REMOVED******REMOVED***
          GIST_ID: ${{ secrets.GIST_ID***REMOVED******REMOVED***
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY ***REMOVED******REMOVED***
          SCU_KEY: ${{ secrets.SCU_KEY ***REMOVED******REMOVED***
