name: Update gist with WakaTime summary
on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 09,21 * * *'
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: ./
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID}}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SCU_KEY: ${{ secrets.SCU_KEY }}
